### PR TITLE
Add extra check when resolving INFOPLIST_FILE and fail with a meaningful error message

### PR DESCRIPTION
**Pull request by ianbytchek**
This takes care when INFOPLIST_FILE setting fails to resolve, which can happen [here](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/blob/v0.3.4/lib/fastlane/plugin/versioning/actions/get_info_plist_path.rb#L40) and [here](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/blob/v0.3.4/lib/fastlane/plugin/versioning/actions/get_info_plist_path.rb#L43) without an actual error raised.

### CODE REVIEW

**Comment by ianbytchek** [comment]
This is partly a continuation of my quest with #13. Looks like it's failing because of a very old fastlane. Can we upgrade it to something higher?

**Comment by SiarheiFedartsou** [comment]
@ianbytchek Thanks for PR. Yes, of course, we can update fastlane version. Could you do it?

**Comment by ianbytchek** [comment]
This isn't outdated Fastlane… Before I dig further can you help me out a little?

[Here](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/blob/v0.3.4/lib/fastlane/plugin/versioning/actions/get_info_plist_path.rb#L49) you have:

```ruby
path = plist.gsub('$(SRCROOT)', project.path.parent.to_path)
path = path.gsub('${SRCROOT}', project.path.parent.to_path)
```

This is what failing current tests – when variables are resolved it simply returns `SRCROOT`, not `$(SRCROOT)`. I'd expect it to be an actual expanded path, but instead Xcodeproj returns variable name.

Do you know anything about this? Why? Doesn't Xcodeproj know that path?

**Comment by ianbytchek** [comment]
🚦Green light!!!

**Comment by ianbytchek** [comment]
@SiarheiFedartsou 👋 Can we merge this? Rebased everything onto the latest version. Looks good from my end.

**Comment by SiarheiFedartsou** [comment]
@ianbytchek Yes, of course, we can. And maybe you want to be a maintainer of this repo? :) Unfortunately, for now I don't have enough time to support this plugin...

**Comment by ianbytchek** [comment]
Feel free to add me to the maintainers list. I know my way a around the project a little, will contribute with what I can! 👍

**Comment by SiarheiFedartsou** [comment]
@ianbytchek Thanks for accepting this proposition :) Added you as collaborator for now. As I understood it is the only thing that I can do without moving this repo to another account/organization. But it will be enough to support it.

**Pull request merged**
