### PR TITLE
Handle version number set at project level

### PR DESCRIPTION
**Pull request by paynerc**
While setting up fastlane for a work project I ran into an issue because we set our version number at the project level. I noticed that two issues were raised that seem to be related, #72 and #98.

For retrieving version number, if the `target` or `scheme` is not provided, it will first attempt to get the version from the project level. If one is not defined, it defaults back to the original methodology and if there is more than one scheme, it will prompt you to select one.

For setting the version number, if it is determined that the version is set at the project level, it will update it there, otherwise it is business as usual.

### CODE REVIEW

**Comment by jdouglas-nz** [comment]
thank you for the contribution @paynerc ! and apologies for the delay in getting around to this. all looks good to me, tests all pass, will merge then ship.

**Review by jdouglas-nz — APPROVED** [review]

**Comment by simon-assistiq** [comment]
What about doing this for the `CURRENT_PROJECT_VERSION`?

**Comment by letrongh** [comment]
Hello,

With version 0.7.0 and your fix, my version number was not updated anymore because I have set it at target level. So, I have just removed at target and set only at project level and it works great.

In my case it's ok but if you need to set at target level, the plugin will write the version at project + target, and next time, it will only change at project level. Or I have missed something?

Thanks

**Comment by paynerc** [comment]
To continue to do target versioning you just have to specify the target you want to update with the options.

**Pull request merged**
