### PR TITLE
Handle 302 HTTP responses in get_app_store_version_number action

### PR DESCRIPTION
**Pull request by josej14**
This is a fix for #105:

- Hardcoded iTunes Search API url using `https` instead of `http`
- Handle any other 302 http response to perform a new request to `response.location` url provided from initial response

### CODE REVIEW

**Comment by josej14** [comment]
@SiarheiFedartsou would appreciate your feedback on this. Thanks!

**Comment by jdouglas-nz** [comment]
@josej14 thank you for the contribution!  would you be able to write a test for this?

**Comment by josej14** [comment]
> @josej14 thank you for the contribution! would you be able to write a test for this?

Sure thing! Didn't see the spec files. These changes may break some tests per the URL change. I'll update them and lyk. Thanks!

**Comment by josej14** [comment]
@jdouglas-nz updated tests helpers and cover HTTP 302 scenario in `get_app_store_version_number_spec.rb`. Please lmk if it looks good to you. Thank you!

**Comment by jdouglas-nz** [comment]
@aamagda today! (As in, within hours).Thanks for the bump

**Review by jdouglas-nz — APPROVED** [review]

**Pull request merged**
